export const footerLinks = [
  {
    title: 'بیماری‌ها',
    links: [
      { title: 'مشاوره و درمان', url: '/darman' },
      { title: 'دیابت', url: '/diabet' },
      { title: 'اختلالات هورمونی', url: '/' },
      { title: 'کبد چرب و چاقی', url: '/' },
      { title: 'زایمان و سزارین', url: '/' },
      { title: 'جراحیهای زیبایی زنان', url: '/' },
      { title: 'عفونت‌های واژینال', url: '/' },
      { title: 'پوکی استخوان', url: '/' },
      { title: 'کورتاژ', url: '/' },
      { title: 'بیماری‌های عفونی', url: '/' },
      { title: 'عفونت‌های تنفسی', url: '/' },
      { title: 'عفونت‌های کلیوی و گوارشی', url: '/' },
      { title: 'هپاتیت', url: '/' },
      { title: 'بیماری‌های آمیزشی', url: '/' },
      { title: 'بیماریهای دستگاه تناسلی', url: '/' },
      { title: 'عفونت‌ زخم', url: '/' },
    ],
  },
  {
    title: 'دکترها',
    links: [
      { title: 'نژلا ابریشم‌چیان', url: '/' },
      { title: 'شیوا توتونیان', url: '/' },
      { title: 'کتایون طایری', url: '/' },
      { title: 'سوزان هاشمی فشارکی', url: '/' },
      { title: 'آزاده اسحاقیان', url: '/' },
      { title: 'پردیس کاوه', url: '/' },
      { title: 'محمد مهدی پیرمرادیان', url: '/' },
      { title: 'پیمان اکبری', url: '/' },
      { title: 'فرشاد پرهام', url: '/' },
      { title: 'مهری امان الهی', url: '/' },
    ],
  },
  {
    title: 'عمومی',
    links: [
      { title: 'تزریق وریدی و ماهیچه‌ای', url: '/' },
      { title: 'نوار قلب', url: '/' },
      { title: 'بخیه و پانسمان', url: '/' },
      { title: 'مشاوره و درمان', url: '/' },
      { title: 'تزریق ژل و بوتاکس', url: '/' },
      { title: 'لیزر موهای زائد', url: '/' },
    ],
  },

  {
    title: 'بخش‌ها',
    links: [
      { title: 'عمومی', url: '/' },
      { title: 'غدد و متابولیسم', url: '/' },
      { title: 'زنان و زایمان', url: '/' },
      { title: 'بیماری‌های عفونی', url: '/' },
      { title: 'کودکان و نوزادان', url: '/' },
      { title: 'فیزیوتراپی', url: '/' },
    ],
  },
]
export const illnessList: Options[] = [
  { title: 'دیابت', value: 'دیابت', url: '/' },
  { title: 'اختلالات هورمونی', value: 'اختلالات هورمونی', url: '/' },
  { title: 'کبد چرب و چاقی', value: 'کبد چرب و چاقی', url: '/' },
  { title: 'زایمان و سزارین', value: 'زایمان و سزارین', url: '/' },
  { title: 'جراحیهای زیبایی زنان', value: 'جراحیهای زیبایی زنان', url: '/' },
  { title: 'عفونت‌های واژینال', value: 'عفونت‌های واژینال', url: '/' },
  { title: 'پوکی استخوان', value: 'پوکی استخوان', url: '/' },
  { title: 'کورتاژ', value: 'کورتاژ', url: '/' },
  { title: 'بیماری‌های عفونی', value: 'بیماری‌های عفونی', url: '/' },
  { title: 'عفونت‌های تنفسی', value: 'عفونت‌های تنفسی', url: '/' },
  {
    title: 'عفونت‌های کلیوی و گوارشی',
    value: 'عفونت‌های کلیوی و گوارشی',
    url: '/',
  },
  { title: 'هپاتیت', value: 'هپاتیت', url: '/' },
  { title: 'بیماری‌های آمیزشی', value: 'بیماری‌های آمیزشی', url: '/' },
  {
    title: 'بیماریهای دستگاه تناسلی',
    value: 'بیماریهای دستگاه تناسلی',
    url: '/',
  },
  { title: 'عفونت‌ زخم', value: 'عفونت‌ زخم', url: '/' },
  {
    title: 'تزریق وریدی و ماهیچه‌ای',
    value: 'تزریق وریدی و ماهیچه‌ای',
    url: '/',
  },
  { title: 'نوار قلب', value: 'نوار قلب', url: '/' },
  { title: 'بخیه و پانسمان', value: 'بخیه و پانسمان', url: '/' },
  { title: 'مشاوره و درمان', value: 'مشاوره و درمان', url: '/' },
  { title: 'تزریق ژل و بوتاکس', value: 'تزریق ژل و بوتاکس', url: '/' },
  { title: 'لیزر موهای زائد', value: 'لیزر موهای زائد', url: '/' },
]
export const doctorsList: Options[] = [
  { title: 'نژلا ابریشم‌چیان', value: 'نژلا ابریشم‌چیان', url: '/' },
  { title: 'شیوا توتونیان', value: 'شیوا توتونیان', url: '/' },
  { title: 'کتایون طایری', value: 'کتایون طایری', url: '/' },
  { title: 'سوزان هاشمی فشارکی', value: 'سوزان هاشمی فشارکی', url: '/' },
  { title: 'آزاده اسحاقیان', value: 'آزاده اسحاقیان', url: '/' },
  { title: 'پردیس کاوه', value: 'پردیس کاوه', url: '/' },
  { title: 'محمد مهدی پیرمرادیان', value: 'محمد مهدی پیرمرادیان', url: '/' },
  { title: 'پیمان اکبری', value: 'پیمان اکبری', url: '/' },
  { title: 'فرشاد پرهام', value: 'فرشاد پرهام', url: '/' },
  { title: 'مهری امان الهی', value: 'مهری امان الهی', url: '/' },
]
export const specialist: Options[] = [
  { title: 'غدد و متابولیسم', value: 'غدد و متابولیسم' },
  { title: 'زنان و زایمان', value: 'زنان و زایمان' },
  { title: 'بیماری‌های عفونی', value: 'بیماری‌های عفونی' },
  { title: 'کودکان و نوزادان', value: 'کودکان و نوزادان' },
]
export const allLinks = [
  {
    label: 'بیماری‌ها',
    title: 'illness',
    links: [
      { title: 'تزریق وریدی و ماهیچه‌ای', url: '/' },
      { title: 'نوار قلب', url: '/' },
      { title: 'بخیه و پانسمان', url: '/' },
      { title: 'مشاوره و درمان', url: '/' },
      { title: 'تزریق ژل و بوتاکس', url: '/' },
      { title: 'لیزر موهای زائد', url: '/' },
      { title: 'مشاوره و درمان', url: '/' },
      { title: 'دیابت', url: '/' },
      { title: 'اختلالات هورمونی', url: '/' },
      { title: 'کبد چرب و چاقی', url: '/' },
      { title: 'زایمان و سزارین', url: '/' },
      { title: 'جراحیهای زیبایی زنان', url: '/' },
      { title: 'عفونت‌های واژینال', url: '/' },
      { title: 'پوکی استخوان', url: '/' },
      { title: 'کورتاژ', url: '/' },
      { title: 'بیماری‌های عفونی', url: '/' },
      { title: 'عفونت‌های تنفسی', url: '/' },
      { title: 'عفونت‌های کلیوی و گوارشی', url: '/' },
      { title: 'هپاتیت', url: '/' },
      { title: 'بیماری‌های آمیزشی', url: '/' },
      { title: 'بیماریهای دستگاه تناسلی', url: '/' },
      { title: 'عفونت‌ زخم', url: '/' },
    ],
  },
  {
    label: 'بخش‌ها',
    title: 'parts',
    links: [
      { title: 'عمومی', url: '/' },
      { title: 'غدد و متابولیسم', url: '/' },
      { title: 'زنان و زایمان', url: '/' },
      { title: 'بیماری‌های عفونی', url: '/' },
      { title: 'کودکان و نوزادان', url: '/' },
      { title: 'فیزیوتراپی', url: '/' },
    ],
  },
  {
    label: 'دکترها',
    title: 'doctors',
    links: [
      { title: 'نژلا ابریشم‌چیان', url: '/' },
      { title: 'شیوا توتونیان', url: '/' },
      { title: 'کتایون طایری', url: '/' },
      { title: 'سوزان هاشمی فشارکی', url: '/' },
      { title: 'آزاده اسحاقیان', url: '/' },
      { title: 'پردیس کاوه', url: '/' },
      { title: 'محمد مهدی پیرمرادیان', url: '/' },
      { title: 'پیمان اکبری', url: '/' },
      { title: 'فرشاد پرهام', url: '/' },
      { title: 'مهری امان الهی', url: '/' },
    ],
  },
]

////////////////////////////ORGANIZED///////////////////////////////////////
export const days: Days[] = [
  { id: 1, name: 'شنبه' },
  { id: 2, name: 'یکشنبه' },
  { id: 3, name: 'دوشنبه' },
  { id: 4, name: 'سه‌شنبه' },
  { id: 5, name: 'چهارشنبه' },
  { id: 6, name: 'پنجشنبه' },
]
export const doctors: Doctors[] = [
  {
    id: 1,
    name: 'نژلا ابریشم‌چیان',
    illnessId: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    url: '/abrishamchian',
    imageSrc: '/images/1.png',
    specialty: ['فوق تخصص غدد و متابولیسم بالغین'],
    booking: [
      { dayId: 2, hours: ['14', '17'] },
      { dayId: 3, hours: ['14', '17'] },
    ],
  },
  {
    id: 2,
    name: 'شیوا توتونیان',
    illnessId: [
      13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    ],
    url: '/toutounian',
    imageSrc: '/images/1.png',
    specialty: ['جراح و متخصص زنان و زایمان'],
    booking: [
      { dayId: 2, hours: ['11', '13'] },
      { dayId: 4, hours: ['15:30', '17:30'] },
    ],
  },
  {
    id: 3,
    name: 'کتایون طایری',
    illnessId: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    url: '/taeti',
    imageSrc: '/images/1.png',
    specialty: ['متخصص بیماری‌های عفونی ', 'فلوشیپ AIDS/HIV بالینی'],
    booking: [
      { dayId: 3, hours: ['16', '20'] },
      { dayId: 6, hours: ['13:30', '15:30'] },
    ],
  },
  {
    id: 4,
    name: 'سوزان هاشمی فشارکی',
    illnessId: [44, 45],
    url: '/hashemi',
    imageSrc: '/images/1.png',
    specialty: ['دارای بورد تخصصی کودکان و نوزادان'],
    booking: [
      { dayId: 1, hours: ['10', '12'] },
      { dayId: 3, hours: ['10', '12'] },
      { dayId: 5, hours: ['10', '12'] },
    ],
  },
  {
    id: 5,
    name: 'آزاده اسحاقیان',
    illnessId: [46],
    url: '/eshaghian',
    imageSrc: '/images/1.png',
    specialty: ['پزشک عمومی'],
  },
  {
    id: 6,
    name: 'پردیس کاوه',
    illnessId: [46],
    url: '/kaveh',
    imageSrc: '/images/1.png',
    specialty: ['پزشک عمومی'],
  },
  {
    id: 7,
    name: 'محمد مهدی پیرمرادیان',
    illnessId: [46],
    url: '/pirmoradian',
    imageSrc: '/images/1.png',
    specialty: ['پزشک عمومی'],
  },
  {
    id: 8,
    name: 'پیمان اکبری',
    illnessId: [46],
    url: '/akbari',
    imageSrc: '/images/1.png',
    specialty: ['پزشک عمومی'],
  },
  {
    id: 9,
    name: 'فرشاد پرهام',
    illnessId: [46],
    url: '/parham',
    imageSrc: '/images/1.png',
    specialty: ['پزشک عمومی'],
  },
  {
    id: 10,
    name: 'مهری امان الهی',
    illnessId: [47],
    url: '/amanolahi',
    imageSrc: '/images/1.png',
    specialty: ['فیزیوتراپیست'],
  },
]

export const illness: Illness[] = [
  { id: 1, name: 'دیابت', doctorId: [1] },
  { id: 2, name: 'بیماری‌های هیپوفیز', doctorId: [1] },
  { id: 3, name: 'اختلالات پروکلاتین', doctorId: [1] },
  { id: 4, name: 'اختلالات هورمونی', doctorId: [1] },
  { id: 5, name: 'تنبلی تخمدان', doctorId: [1] },
  { id: 6, name: 'بیماری‌های غده فوق کلیه', doctorId: [1] },
  { id: 7, name: 'فشارخونهای ثانویه', doctorId: [1] },
  { id: 8, name: 'پوکی استخوانها', doctorId: [1] },
  { id: 9, name: 'اختلالات رشد', doctorId: [1] },
  { id: 10, name: 'سندروم متابولیک', doctorId: [1] },
  { id: 11, name: 'کبد چرب', doctorId: [1] },
  { id: 12, name: 'چاقی', doctorId: [1] },
  { id: 13, name: 'زایمان طبیعی', doctorId: [2] },
  { id: 14, name: 'جراحی زیبایی زنان', doctorId: [2] },
  { id: 15, name: 'RF', doctorId: [2] },
  { id: 16, name: 'لیزر زنان', doctorId: [2] },
  { id: 17, name: 'افتادگی واژن', doctorId: [2] },
  { id: 18, name: 'اختلالات قاعدگی', doctorId: [2] },
  { id: 19, name: 'عفونت واژینال', doctorId: [2] },
  { id: 20, name: 'مراقبت‌های یائسگی', doctorId: [2] },
  { id: 21, name: 'پوکی استخوان', doctorId: [2] },
  { id: 22, name: 'خشکی واژن', doctorId: [2] },
  { id: 23, name: 'اختلالات ادراری زنان', doctorId: [2] },
  { id: 24, name: 'مراقبت‌های بارداری', doctorId: [2] },
  { id: 25, name: 'پاپ اسمیر', doctorId: [2] },
  { id: 26, name: 'معاینه پستان', doctorId: [2] },
  { id: 27, name: 'IUD', doctorId: [2] },
  { id: 28, name: ' کورتاژ', doctorId: [2] },
  { id: 29, name: 'هیسترکتومی(خارج نمودن رحم)', doctorId: [2] },
  { id: 30, name: 'مشاوره بارداری', doctorId: [2] },
  { id: 31, name: 'بیماری‌های عفونی', doctorId: [3] },
  { id: 32, name: 'بیماری‌های تب‌دار', doctorId: [3] },
  { id: 33, name: 'عفونت‌های تنفسی', doctorId: [3] },
  { id: 34, name: 'کوید 19', doctorId: [3] },
  { id: 35, name: 'انفلوآنزا', doctorId: [3] },
  { id: 36, name: 'عفونت‌های کلیوی', doctorId: [3] },
  { id: 37, name: 'عفونت‌های گوارشی', doctorId: [3] },
  { id: 38, name: 'بیماری‌ها آمیزشی', doctorId: [3] },
  { id: 39, name: 'زگیل تناسلی', doctorId: [3] },
  { id: 40, name: 'تبخال تناسلی', doctorId: [3] },
  { id: 41, name: 'سوزاک', doctorId: [3] },
  { id: 42, name: 'عفونت زخم', doctorId: [3] },
  { id: 43, name: 'عفونت دوران بارداری', doctorId: [3] },
  { id: 44, name: 'متخصص کودکان', doctorId: [4] },
  { id: 45, name: 'متخصص نوزادان', doctorId: [4] },
  { id: 46, name: 'عمومی', doctorId: [5, 6, 7, 8, 9] },
  { id: 47, name: 'فیزیوتراپی', doctorId: [10] },
]

export const special: Special[] = [
  { id: 1, name: 'غدد و متابولیسم', doctorId: [1] },
  { id: 2, name: 'زنان و زایمان', doctorId: [2] },
  { id: 3, name: 'بیماری‌های عفونی', doctorId: [3] },
  { id: 4, name: 'کودکان و نوزادان', doctorId: [4] },
]
